### ISSUE TITLE
Add COS integration

### ISSUE THREAD

**Issue by mthaddon** [canonical/redis-k8s-operator#51]
When running this charm in a production setting it would be useful to be able to integrate it with [COS](https://charmhub.io/topics/canonical-observability-stack) to get metrics/dashboards for the application.

**Comment by reneradoi** [comment]
Resolved with https://github.com/canonical/redis-k8s-operator/pull/61.

As of revision 29 in `latest/edge`, this charm now supports COS lite. Please make sure to pull the new image when updating, e.g. with `juju refresh ... --resource redis-image=ghcr.io/canonical/charmed-redis:7.2.5-22.04-edge`.

Redis metrics can be found in the dashboard `Redis Dashboard for Prometheus Redis Exporter` under `General`.

Other than that, the following changes are included in this revision:
- update to version 7.2.5 of redis
- redis now runs in `appendonly` mode by default in order to avoid data loss (see also: https://redis-stack.io/docs/management/persistence/)
